project_id = "nvfioycpwyzwukvokwql"

[functions.telegram-webhook]
verify_jwt = false

[functions.join-team]
verify_jwt = false

[functions.vapid-keys]
verify_jwt = false

[functions.send-push]
verify_jwt = false

[functions.invite-member]
verify_jwt = false
