project_id = "nvfioycpwyzwukvokwql"

[functions]
  [functions.ai-assistant]
    verify_jwt = false
  [functions.auth-email-hook]
    verify_jwt = false
  [functions.auto-baseline-lock]
    verify_jwt = false
  [functions.calendar-feed]
    verify_jwt = false
  [functions.dashboard-report]
    verify_jwt = false
  [functions.invite-member]
    verify_jwt = false
  [functions.join-team]
    verify_jwt = false
  [functions.notify-new-user]
    verify_jwt = false
  [functions.process-email-queue]
    verify_jwt = true
  [functions.admin-update-user]
    verify_jwt = false
  [functions.send-chat-telegram]
    verify_jwt = false
  [functions.send-push]
    verify_jwt = false
  [functions.suggest-tags]
    verify_jwt = false
  [functions.telegram-2fa]
    verify_jwt = false
  [functions.telegram-webhook]
    verify_jwt = false
  [functions.vapid-keys]
    verify_jwt = false
  [functions.max-webhook]
    verify_jwt = false
  [functions.send-chat-max]
    verify_jwt = false
