// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Cloudflare Worker proxy for REST/Auth/Storage/Functions (faster from RU).
// Realtime (WebSocket) keeps direct Supabase URL — Worker не проксирует WS.
const WORKER_URL = 'https://round-morning-5599.avedyaev.workers.dev';

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(WORKER_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
});

// Realtime: переопределяем endpoint на прямой Supabase URL (Worker не проксирует WebSocket).
// Делаем через приватное поле клиента, т.к. supabase-js не даёт публичного API
// сменить URL Realtime отдельно от REST.
try {
  const directWsUrl = `${SUPABASE_URL.replace(/^http/, 'ws')}/realtime/v1`;
  // @ts-ignore — internal field
  supabase.realtime.endPoint = `${directWsUrl}/websocket`;
  // @ts-ignore — internal field
  supabase.realtimeUrl = directWsUrl;
} catch (err) {
  console.warn('[supabase] failed to override realtime endpoint', err);
}